kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: canary-check
spec:
  metrics:
    - name: test
      interval: 1m
      successCondition: result[0] >= 0
      failureLimit: 0
      provider:
        prometheus:
          address: {{ .Values.prometheus.address }}
          query: |
            sum(rate(cart_value_count{service="web-canary"}[1m])) by (service)
